headerPath = "ci/license-header.txt"

includes = [
    "*.c",
    # "*.java", # TODO
    "*.sh",
]

excludes = [
    # The format script is checked by hawkeye, but on fresh CI clones the disk
    # timestamp may differ from git modification year causing false positives.
    ".bazelci/format.sh",
]

[git]
attrs = 'auto'
ignore = 'auto'

[properties]
copyrightOwner = "The Buildfarm Authors"

[mapping.DOUBLESLASH_STYLE]
extensions = ["java"]
