name: Build and Push Latest Buildfarm Images

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'buildfarm/buildfarm'
    name: Build Buildfarm Images
    runs-on: ubuntu-latest
    steps:
    - uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2   # v3

    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0

    - name: Login to Bazelbuild Docker Hub
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1   # v3
      with:
        username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
        password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}

    - name: Build Server Image
      id: buildAndPushServerImage
      run: bazel run //container:public_push_buildfarm-server -- --tag latest

    - name: Build Worker Image
      id: buildAndPushWorkerImage
      run: bazel run //container:public_push_buildfarm-worker -- --tag latest
