name: Build and Push Latest Buildfarm Images

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'buildfarm/buildfarm'
    name: Build Buildfarm Images
    runs-on: ubuntu-latest
    steps:
    - uses: bazel-contrib/setup-bazel@083175551ceeceebc757ebee2127fde78840ca77   # 0.18.0
      with:
          # Avoid downloading Bazel every time.
        bazelisk-cache: true

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2

    - name: Login to Bazelbuild Docker Hub
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9   # v3.7.0
      with:
        username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
        password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}

    - name: Build Server Image
      id: buildAndPushServerImage
      run: bazel run //container:public_push_buildfarm-server -- --tag latest

    - name: Build Worker Image
      id: buildAndPushWorkerImage
      run: bazel run //container:public_push_buildfarm-worker -- --tag latest
