name: Build and Push Buildfarm Releases

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'buildfarm/buildfarm'
    name: Build Buildfarm Images
    runs-on: ubuntu-latest
    steps:
    - uses: bazel-contrib/setup-bazel@4fd964a13a440a8aeb0be47350db2fc640f19ca8   # 0.15.0
      with:
          # Avoid downloading Bazel every time.
        bazelisk-cache: true

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2

    - name: Login to Bazelbuild Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef   # v3.6.0
      with:
        username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
        password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}

    - name: Build Server Image
      id: buildAndPushServerImage
      run: bazel run //container:public_push_buildfarm-server -- --tag ${{ github.event.release.tag_name }}

    - name: Build Worker Image
      id: buildAndPushWorkerImage
      run: bazel run //container:public_push_buildfarm-worker -- --tag ${{ github.event.release.tag_name }}
